spring.application.name=demo
sparrow.token=v2_xrihREm2vQV5taKVSTQgYRXZvdw.zdiR
sparrow.sender=Demo
# Use the PORT environment variable provided by Render, or 10000 as a fallback
server.port=${PORT:10000}
server.address=0.0.0.0